### ISSUE TITLE
problem with install on windows

### ISSUE THREAD

**Issue by Mexiswow** [ryanatkn/nutrients-per-calorie#3]
Hi, a have a problem with install...
I have last version Node.js, Coffee-Script and Compass
i download nutrients-per-calorie and i tried install and start it.

Have this errors
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! nutrients-per-calorie@0.1.0 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nutrients-per-calorie@0.1.0 start script 'gulp'.
npm ERR! This is most likely a problem with the nutrients-per-calorie package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls nutrients-per-calorie
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Mex\Desktop\nutrients\npm-debug.log

**Comment by ryanatkn** [comment]
I forgot to add gulp to the readme's installation instructions when I changed the build tools. I think `npm install -g gulp` should fix the issue. Thanks for the report.
